language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - $HOME/.composer

env:
  global:
    - SYMFONY_ENV=test

before_script:
  - composer self-update
  - composer install --prefer-dist --dev

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs
