language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - $HOME/.composer

env:
  global:
    - SYMFONY_ENV=test

before_script:
  - composer self-update
  - composer install --prefer-dist --dev

script:
  - phpunit --configuration ./phpunit.xml --coverage-clover ./build/logs/clover.xml
#  - ./application/bin/phpcs --standard=PSR2 application/src/
